server:
  port: 8090
  servlet:
    context-path: /demo
spring:
  rabbitmq:
    host: 111.229.240.182
    port: 5672

    username: guest
    password: guest
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    connection-timeout: 60000

